- app.js
- avAdmin/elections-api-service.js
- bower.json
- index.html
When creating an election, saves it in HTML5 local storage instead of in a cookie because the cookie headers would be otherwise very large. Related trello card: https://trello.com/c/EEWKlGQ9/462-recargar-la-pagina-de-nueva-votacion-en-el-navegador-da-error-400-request-entity-too-large
> Save election local storage

- avAdmin/admin-directives/elcensus/elcensus.js
When in an election with email census, in agora-gui-admin > census > add from CSV, we add a list of emails with some spaces between the emails, currently this adds the emails with the spaces and this makes login later fail.
TODO: Fix that also in authapi! @virako maybe can you do it, with a test case?
> fix spaces when adding from csv

- avAdmin/admin-directives/elcensus/elcensus.html
- avAdmin/admin-directives/elcensus/elcensus.js
- avAdmin/admin-directives/elcensus/elcensus.less
- locales/en.json
- locales/es.json
This patch adds actions buttons for each row in the census table.
Buttons added are Activate, Deactivate, Remove and Send auth codes.
These buttons select the row and then call the same action as actions
dropdown, all other rows are deselected so this should work similar to
select only one row and click in the actions dropdown.
Buttons are hidden by default and showed on hover the row.
I've add translations for these actions but not for gl and ca.
> census: Add action buttons for each voter

- avAdmin/admin-directives/activity-log/activity-log.html
- avAdmin/admin-directives/activity-log/activity-log.js
- avAdmin/admin-directives/elcensus/confirm-activate-people-modal.html
- avAdmin/admin-directives/elcensus/confirm-activate-people-modal.js
- avAdmin/admin-directives/elcensus/confirm-deactivate-people-modal.html
- avAdmin/admin-directives/elcensus/confirm-deactivate-people-modal.js
- avAdmin/admin-directives/elcensus/elcensus.js
- avAdmin/admin-directives/elcensus/elcensus.less
- locales/en.json
- locales/es.json
This patch allows comments for activate and deactivate actions. A
textarea is available in the activate action and the content of that
will go as comment.
To show the comment in the activity log I've to change a little the
code because the angular template always resolve the {{obj.metadata.comment}}
as undefined, I don't know why, so I've added other attr to obj called
metadatacomment.
This PR depends on: https://github.com/agoravoting/agora-gui-common/pull/85
> census: Comment for activate/deactivate actions

- avAdmin/admin-directives/question/question.html
- avAdmin/admin-directives/question/question.js
- locales/en.json
This patch adds the cumulative voting tally type.
The cumulative tally_type will only be supported by the
simultaneous questions layout, so this patch ensure that the user
can only select the correct layout/tally_type combination and
shows a descriptive message for the user.
A new extra_option is also added so the
cumulative_number_of_questions could be configured in the admin
interface.
> Add cumulative voting support

- avAdmin/admin-directives/create/create.js
- locales/en.json
In the election creation admin page, when creating [parent-children elections](https://agoravoting.github.io/admin-manual/docs/advanced-elections/parent-and-children-elections) sometimes it fails because parent is not created yet when setting the [children election info](https://agoravoting.github.io/admin-manual/docs/file-formats/election-creation-json#election-children_election_info). This can be easily fixed by first creating the auth-event and registering all the elections in the backend, and only afterwards setting the children-election-info.
> Delayed children election info setting during election creation

- avAdmin/admin-controller/admin-controller.js
It was not detecting that `edit` perms as equivalent to `list-ballot-boxes`.
> fixing ballot box permissions detection in admin-controller

- avAdmin/admin-directives/create/create.html
- avAdmin/admin-directives/create/create.js
- avAdmin/admin-directives/elections/elections.html
There was an issue with election description. During election creation, we relied in ng-bind-html to sanitize the visualization of election description before being sanitized by the backend (because it has not yet been sent to the backend), but apparently it doesn't work for some xss. The same issue happened in election list when showing the description of the draft election.
With this change, we always show the election description as plain text so that we don't need to sanitize it. Also see related issue with htmlToText in common-ui: https://github.com/sequentech/common-ui/pull/221 because sometimes we also called to our own htmlToText angular filter, and sanitization was also needed to happen there.
Another fix is to use $sanitize more pervasively in the election creation screen, so …
> Fix some XSS

- SequentConfig.js
- avAdmin/admin-directives/dashboard/send-auth-codes-modal-confirm.html
- avAdmin/admin-directives/dashboard/send-auth-codes-modal-confirm.js
- avAdmin/admin-directives/dashboard/send-auth-codes-modal.html
- avAdmin/admin-directives/dashboard/send-auth-codes-modal.js
- avAdmin/admin-directives/elauth/elauth.html
- avAdmin/admin-directives/elauth/elauth.js
- locales/en.json
- locales/es.json
* Allow to configure both plain-text and HTML email body when sending email codes both from the dashboard and in the census tab to specific voters, and configure it to actually integrate with the IAM backend properly.
* Allow to configure both plain-text and HTML email body when creating the election.  
* Show a preview of the html message before sending it.
> Support HTML format when sending email auth-codes

- avAdmin/admin-directives/dashboard/dashboard.less
- avAdmin/admin-directives/dashboard/send-auth-codes-modal-confirm.html
- avAdmin/admin-directives/dashboard/send-auth-codes-modal-confirm.js
- avAdmin/admin-directives/dashboard/send-auth-codes-modal.html
- avAdmin/admin-directives/dashboard/send-auth-codes-modal.js
- avAdmin/send-messages-service.js
- locales/ca.json
- locales/en.json
- locales/es.json
Enable sending emails/sms messages to part of the census, filtering by whether the voters have already casted their vote or not.
* Add an option to send messages to part of the census: either those that have voted or those that haven't voted yet.
* Show that option in the modal, only when sending to the whole census and not for individual users.
* Add translations.
Election with email authentication:
Election with SMS authentication:
> Support sending reminders to voters who didn't cast a vote

- yarn.lock
[Merge features into 7.1.x](https://github.com/sequentech/admin-console/pull/313)
> Bump socket.io-parser from 4.0.4 to 4.0.5

- yarn.lock
[Merge features into 6.1.x](https://github.com/sequentech/admin-console/pull/313)
> Bump socket.io-parser from 4.0.4 to 4.0.5 (#313)

- avAdmin/admin-directives/dashboard/delete-share-ceremony-modal.js
- avAdmin/admin-directives/dashboard/download-share-ceremony-modal.js
- avAdmin/admin-directives/dashboard/login-trustee-ceremony-modal.js
- avAdmin/admin-directives/dashboard/restore-share-ceremony-modal.js
Http requests in Chrome can have empty `statusText` fields. This means error messages are not shown in the ceremonies on Chrome.
> Error message is not shown on Chrome (Ceremony)

- avAdmin/admin-directives/create/create.html
- avAdmin/admin-directives/create/create.js
- avAdmin/admin-directives/create/create.less
- locales/en.json
- locales/es.json
This PR adds the ability to open the live preview for an election before creating the election.
* In the last step of the election creation, the pencil button for editing the election json is removed.
* Instead, an actions dropdown menu is added, with two options: Edit JSON and Live Preview.
* When the Live Preview option is clicked, the Election creation JSON is stored in `sessionStorage` and the live preview voting booth is opened in another tab.
* Parent-children elections must define the election ids. A check has been added and an error is shown in the case the ids are missing. If there's an error checking the election creation Json, the Live Preview option will become unavailable.
* As the data passed to the voting booth is the Election creation JSON, the process of converting that …
> Live preview  (#323)

- avAdmin/admin-directives/create/create.js
Automate filling in election IDs. If the election ID in the Election JSON is negative, replace it with new Election IDs.
* Add new method `fillInElectionIds`. The method detects wether there's any election ID with negative numbers, if there isn't any it returns the election json unmodified.
* If there is a negative election ID, make a call to the auth api (IAM) to find out the highest existing election ID. Use that to replace the negative election IDs with new election IDs.
* Call the new method `fillInElectionIds` after editing the election JSON.
> Election IDs automation

- avAdmin/admin-directives/create/create.js
Automate filling in election IDs. If the election ID in the Election JSON is negative, replace it with new Election IDs.
* Add new method `fillInElectionIds`. The method detects wether there's any election ID with negative numbers, if there isn't any it returns the election json unmodified.
* If there is a negative election ID, make a call to the auth api (IAM) to find out the highest existing election ID. Use that to replace the negative election IDs with new election IDs.
* Call the new method `fillInElectionIds` after editing the election JSON.
> Election IDs automation (#330)

- avAdmin/admin-controller/admin-controller-spec.js
- avAdmin/admin-controller/admin-controller.js
- avAdmin/admin-directives/create/create.js
- avAdmin/automatic-ids-service.js
- index.html
* wip
* wip
* wip
* wip
* fix
* add service
* wip
* fix tests
> Import button should implement automatic ids (#342)

- avAdmin/admin-directives/elcensus/elcensus.js
Parent issue: https://github.com/sequentech/meta/issues/64
In the admin portal, when the census tab of an election is loaded directly (instead of arriving there by clicking from another screen), it shows a scary red error.
Fix it so that this scary error does not show, and the system loads the election census correctly instead.
> Census admin doesn't login correctly if loaded directly

- avAdmin/admin-directives/dashboard/dashboard.js
Parent issue: #351 
When `election.presentation.election_board_ceremony` is set to `true`, the `start election` action in the election dashboard breadcrumb does not allow to start the election unless the Key Distribution Ceremony has been executed. However, the `Start election` action in the Actions menu does allow it.
This can generate a situation in which votes have been cast, the key distribution ceremony has not been executed, and tally cannot be launched since that action does require also to have executed the election board ceremonies (both key distribution and opening).
Change the `Start election` action in the Actions menu in the Election Dashboard so that it also requires to execute the Key Distribution Ceremony before allowing to start the election when …
> Fix start ceremony

- avAdmin/admin-directives/dashboard/confirm-tally-modal.html
- avAdmin/admin-directives/dashboard/confirm-tally-modal.js
- avAdmin/admin-directives/dashboard/dashboard.js
Parent issue: https://github.com/sequentech/meta/issues/65
- Problem description
Admin console shows two possible avenues for launching the tally: tally all votes and tally active users. But they work very differently, one works with parent-children elections (tally active votes) and the other doesn't.
However this inconvenience is not reflected in the UI. To make things worse, the default selected method is the tally all votes, even for parent-children elections which don't work with that mode.
- Proposed solution
Make both modes (tally all census and tally active voters) work with parent-children elections and make the tally active voters the default.
- Tasks
- Change the `admin-console` to show differently the launch-tally dialog to allow selecting which children elections to choose …
> Unify tallying procedures

- avAdmin/admin-directives/dashboard/confirm-tally-modal.html
- avAdmin/admin-directives/dashboard/confirm-tally-modal.js
- avAdmin/admin-directives/dashboard/dashboard.js
Parent issue: https://github.com/sequentech/meta/issues/65
- Problem description
Admin console shows two possible avenues for launching the tally: tally all votes and tally active users. But they work very differently, one works with parent-children elections (tally active votes) and the other doesn't.
However this inconvenience is not reflected in the UI. To make things worse, the default selected method is the tally all votes, even for parent-children elections which don't work with that mode.
- Proposed solution
Make both modes (tally all census and tally active voters) work with parent-children elections and make the tally active voters the default.
- Tasks
- Change the `admin-console` to show differently the launch-tally dialog to allow selecting which children elections to choose …
> Unify tallying procedures (#357)

- package.json
- yarn.lock
Parent issue: https://github.com/sequentech/meta/issues/83
Related dependabot alert:
https://github.com/sequentech/admin-console/security/dependabot/28
> Bump socket.io-parser from 4.0.4 to 4.2.3 (#369)

- avAdmin/admin-controller/admin-controller.js
- avAdmin/admin-directives/ballot-box/ballot-box.html
- avAdmin/admin-directives/ballot-box/ballot-box.js
- avAdmin/admin-directives/dashboard/dashboard.html
- avAdmin/admin-directives/dashboard/dashboard.js
- avAdmin/admin-directives/elbasic/elbasic.html
- avAdmin/admin-directives/elbasic/elbasic.js
- avAdmin/admin-directives/elcensus/elcensus.html
- avAdmin/admin-directives/elcensus/elcensus.js
- avAdmin/admin-directives/elections/elections.html
- avAdmin/admin-directives/elections/elections.js
- avAdmin/admin-directives/elections/elections.less
- avAdmin/admin-sidebar-directive/admin-sidebar-directive.html
- avAdmin/admin-sidebar-directive/admin-sidebar-directive.js
- avAdmin/init.js
Parent issue: https://github.com/sequentech/meta/issues/127
> ✨ Role-based login for election manager

- avAdmin/admin-directives/create/create.js
- avAdmin/admin-directives/dashboard/dashboard.html
- avAdmin/admin-directives/dashboard/dashboard.js
- avAdmin/admin-directives/dashboard/dashboard.less
- avAdmin/elections-api-service.js
- locales/en.json
- locales/es.json
Parent issue: https://github.com/sequentech/meta/issues/704
> ✨ Check if the authorities are online
