sequentech/admin-console

app.js, avAdmin/admin-controller/admin-controller.html, avAdmin/admin-controller/admin-controller.js, avAdmin/admin-directives/create/create.js, avAdmin/admin-directives/dashboard/dashboard.html, avAdmin/admin-directives/dashboard/dashboard.js, avAdmin/admin-directives/elections/elections.html, avAdmin/admin-head-directive/admin-head-directive.html, avAdmin/admin-head-directive/admin-head-directive.js, avAdmin/admin-head-directive/admin-head-directive.less, avAdmin/elections-api-service.js, locales/ca.json, locales/en.json, locales/es.json, locales/gl.json
Depend on https://github.com/agoravoting/agora_elections/pull/1
=> Flow test2real

app.less, avAdmin/admin-controller/admin-controller.html, avAdmin/admin-directives/elcensus/elcensus.js, avAdmin/admin-modal-directive/admin-modal-directive.html, avAdmin/admin-modal-directive/admin-modal-directive.js, avAdmin/admin-modal-directive/admin-modal-directive.less, avAdmin/admin-plugins.js, avAdmin/elections-api-service.js, index.html, plugins/test/test.js.sample
Depends on:
* https://github.com/agoravoting/agora-gui-admin/pull/4
=> Censushook

Gruntfile.js, package.json
Sometimes it's problematic and it's not needed \cc @danigm
=> remove imagemin, sometimes is problematic

avAdmin/admin-directives/dashboard/dashboard.html, avAdmin/admin-directives/dashboard/dashboard.less, locales/ca.json, locales/en.json, locales/es.json, locales/gl.json
**THIS PR CONTAIN ERRORS:**
I have two button with popover:
- The first, use i18next and translate popover attributte and content os button, but when you build with this button, the popover not working:
<button ng-if="!election.results.questions"                                             
class="btn btn-block btn-lg btn-warning"                                              
popover-placement="bottom"                                                            
data-toggle="popover"                                                                 
popover=""                                                                            
ng-i18next="[popover]avAdmin.notes.thisisATestElection;avAdmin.dashboard.createRealElection">
</button> …
=> Button create election

Gruntfile.js, avAdmin/admin-head-directive/admin-head-directive.html, avAdmin/admin-head-directive/admin-head-directive.js
Required: https://github.com/agoravoting/agora-gui-common/pull/6
=> Click help go to helpUrl in avConfig

avAdmin/admin-directives/create/create.js, avAdmin/elections-api-service.js
Depend on https://github.com/agoravoting/agora_elections/pull/2
=> Extra data

avAdmin/admin-directives/dashboard/send-auth-codes-modal-confirm.js, locales/ca.json, locales/en.json, locales/es.json, locales/gl.json
See https://trello.com/c/PEVzd3jH/504-use-replaces-for-replacing-url-s-and-code-s-instead-of-being-a-template-because-it-s-too-powerful-and-for-example-the-char-makes for details
=> using the new template system for sending auth codes

avAdmin/admin-directives/create/create.js, avAdmin/import-service.js, locales/ca.json, locales/en.json, locales/es.json, locales/gl.json
Translate csv and linked example spreadsheet
=> Translate csv

avAdmin/admin-directives/dashboard/dashboard.js, avAdmin/admin-directives/dashboard/send-auth-codes-modal-confirm.html, avAdmin/admin-directives/dashboard/send-auth-codes-modal-confirm.js, avAdmin/admin-plugins.js
NOTE: Merge https://github.com/agoravoting/agora-gui-admin/pull/31 first
=> Fix num electors

Gruntfile.js, avAdmin/admin-directives/create/create.html, avAdmin/admin-directives/create/create.js, avAdmin/admin-directives/create/edit-election-json-modal.html, avAdmin/admin-directives/create/edit-election-json-modal.js, avAdmin/admin-directives/dashboard/dashboard.html, avAdmin/admin-directives/dashboard/dashboard.js, avAdmin/admin-directives/dashboard/dashboard.less, index.html, locales/ca.json, locales/en.json, locales/es.json, locales/gl.json
- Allow json election edit
- Allow admins to download election data before election result has been published
=> Allowing json election edit

avAdmin/admin-directives/dashboard/dashboard.html
Reverts agoravoting/agora-gui-admin#152
=> Revert "fix dashboard results presentation (order of winners etc)"

avAdmin/admin-directives/dashboard/dashboard.js
the next action was kept disabled
=> improve error handling when changing from in-tally to stopped

app.less, avAdmin/admin-directives/tasks/tasks.html, avAdmin/admin-directives/tasks/tasks.js, avAdmin/admin-directives/tasks/tasks.less, avAdmin/admin-directives/tasks/view-task-logs-modal.html, avAdmin/admin-directives/tasks/view-task-logs-modal.js, avAdmin/admin-directives/tasks/view-task-logs-modal.less, avAdmin/admin-sidebar-directive/admin-sidebar-directive.html, avAdmin/admin-sidebar-directive/admin-sidebar-directive.js, avAdmin/ansi-up-service.js, index.html, locales/en.json, package.json, test/e2e.conf.js, yarn.lock
Implement a function for administrators whereby they can test the overall working of the platform. This will be implemented by automatically launching the full process of an election: registering the election ,creation of the keys, uploading the census, opening the voting period, casting a vote, closing the voting period, tallying, obtaining the results and publishing them.
Tasks:
- Add a `config.agora_gui.enable_self_testing` config.yml option and corresponding options in agora-gui-* `avConfig.js` files.
- agora-dev-box: Install all the  dependencies and add a supervisor daemon to be launched if enabled.
- Create an e2e testing suite in `agora-gui-admin` using protractor to test the whole process of an election.
- Create an `authapi_celery` task to launch the protractor test outputting …
=> Self Test function in Admin UI

package.json, yarn.lock
Reported issues:
https://github.com/agoravoting/agora-gui-common/security/dependabot/6
https://github.com/agoravoting/agora-gui-common/security/dependabot/3
https://github.com/agoravoting/agora-gui-common/security/dependabot/11
=> Fixing some security issues that dependabot reported but couldn't solve

avAdmin/admin-controller/admin-controller.less, avAdmin/admin-sidebar-directive/admin-sidebar-directive.less
* Change action colors to green.
* Fix overflow for modals.
=> Change action colors to green

app.js
Related to [master PR](https://github.com/sequentech/admin-console/pull/294)
* Store the current url/path in the session storage to be used to redirect back to it after login.
=> Redirect to path after admin login

avAdmin/admin-directives/activity-log/activity-log.html, avAdmin/admin-directives/dashboard/dashboard.js, avAdmin/elections-api-service.js, locales/en.json, locales/es.json
* support for publicCandidates election flag
* adding set public/private actions to dasboard
* adding missing i18n
* fix typos
* fix icon
* changing to using iam for setting public candidates
=> support for publicCandidates election flag

avAdmin/admin-controller/admin-controller.less
We don't need a 100k pixels high console.
=> Fix admin bottom

avAdmin/admin-directives/admin-fields/admin-fields.html
6.1.x version of  [this PR](https://github.com/sequentech/admin-console/pull/302)
=> fix green action button for admin fields (#302)

avAdmin/admin-directives/dashboard/dashboard.less, avAdmin/admin-directives/dashboard/send-auth-codes-modal-confirm.html, avAdmin/admin-directives/dashboard/send-auth-codes-modal-confirm.js, avAdmin/admin-directives/dashboard/send-auth-codes-modal.html, avAdmin/admin-directives/dashboard/send-auth-codes-modal.js, avAdmin/send-messages-service.js, locales/ca.json, locales/en.json, locales/es.json
Include changes from [this PR](https://github.com/sequentech/admin-console/pull/306) in version 7.0.x
=> Support sending reminders to voters who didn't cast a vote

avAdmin/admin-controller/admin-controller.js, avAdmin/admin-sidebar-directive/admin-sidebar-directive.html, avAdmin/admin-sidebar-directive/admin-sidebar-directive.js
=> Import button doesn't work on Firefox

avAdmin/automatic-ids-service.js
=> Support census/voters on election id automation

Gruntfile.js, locales/fr.json
Parent issue: https://github.com/sequentech/meta/issues/48
=> French language support

package.json, yarn.lock
Fixes https://github.com/sequentech/admin-console/security/dependabot/25
=> Bump xml2js from 0.4.17 to 0.5.0

package.json, yarn.lock
Fixes https://github.com/sequentech/admin-console/security/dependabot/25
=> Bump xml2js from 0.4.17 to 0.5.0 (#358)

.github/workflows/ort.yml
Parent issue: https://github.com/sequentech/meta/issues/59
Use the reusable workflow from the meta repository instead.
=> Fix ORT Github Workflow (#360)

Gruntfile.js
Parent issue: https://github.com/sequentech/meta/issues/68
=> favicon.ico not loading

Gruntfile.js
Parent issue: https://github.com/sequentech/meta/issues/68
=> favicon.ico not loading (#363)

avAdmin/admin-directives/extra-field/extra-field.html
Parent issue: https://github.com/sequentech/meta/issues/70
=> Can't duplicate election when editing date extra field

Gruntfile.js, app.less, avAdmin/admin-controller/admin-controller.less, avAdmin/admin-directives/create/create.js, avAdmin/admin-directives/create/create.less, avAdmin/admin-directives/dashboard/dashboard.less, avAdmin/admin-directives/elcensus-config/elcensus-config.less, avAdmin/admin-directives/elections/elections.less, avAdmin/admin-directives/elquestions/elquestions.less, avAdmin/admin-directives/question-option-details/question-option-details.less, avAdmin/admin-directives/question/question.less, avAdmin/admin-head-directive/admin-head-directive.less, avAdmin/admin-login-controller/admin-login-controller.html, avAdmin/admin-login-controller/admin-login-controller.less, avAdmin/admin-sidebar-directive/admin-sidebar-directive.less, locales/en.json, locales/es.json
Parent issue: https://github.com/sequentech/voting-booth/issues/304
=> Booth redesign

avAdmin/admin-directives/elquestions/elquestions.less, avAdmin/admin-directives/extra-field/extra-field.less, avAdmin/admin-directives/question-option-details/question-option-details.less
Parent Issue: https://github.com/sequentech/meta/issues/113
=>  Fix css issues on admin console (#371)

avAdmin/admin-directives/dashboard/send-auth-codes-modal-confirm.js, avAdmin/admin-directives/dashboard/send-auth-codes-modal-confirm.less, avAdmin/elections-api-service.js
Parent issue: https://github.com/sequentech/epi/issues/114
=> Alternative Auth methods support

avAdmin/admin-directives/elcensus/elcensus.html, avAdmin/admin-directives/elcensus/elcensus.js
Parent issue: https://github.com/sequentech/meta/issues/129
=> 🐞 Census menu translations don't always work

avAdmin/admin-directives/elcensus/elcensus.html, avAdmin/admin-directives/elcensus/elcensus.js
Parent issue: https://github.com/sequentech/meta/issues/129
=> 🐞 Census menu translations don't always work (#376)

SequentConfig.js
Parent issue: https://github.com/sequentech/epi/issues/19
=> ✨ Countdown until logout

Gruntfile.js, SequentConfig.js, index.html, package.json
Parent issue: https://github.com/sequentech/meta/issues/136
=> `master` branch should be using `master` version number and not `8.0.0` 

package.json, yarn.lock
Parent issue: https://github.com/sequentech/meta/issues/135
=> Security updates: word-wrap resolution

package.json, yarn.lock
Parent issue: https://github.com/sequentech/meta/issues/135
=> Security updates: word-wrap resolution (#380)

avAdmin/admin-directives/ballot-box/view-tally-sheet-modal.html, avAdmin/admin-directives/ballot-box/write-tally-sheet-modal.html, avAdmin/admin-directives/create/create.html, avAdmin/admin-directives/dashboard/dashboard.html, avAdmin/admin-directives/dashboard/send-auth-codes-modal.js, avAdmin/admin-directives/elections/elections.html, avAdmin/admin-sidebar-directive/admin-sidebar-directive.html
Parent issue: https://github.com/sequentech/meta/issues/122
=> ✨ Multilingualism

SequentConfig.js, avAdmin/csv-load-service.js
Parent issue: https://github.com/sequentech/meta/issues/119
=> 🐞 add census data second batch will not be executed

SequentConfig.js
Parent issue: https://github.com/sequentech/meta/issues/119
=> 🐞 add census data second batch will not be executed (#384)

SequentConfig.js, avAdmin/admin-directives/dashboard/dashboard.js, locales/en.json
Parent issue: https://github.com/sequentech/meta/issues/146
=> ✨ Enable progressive tallies 

avAdmin/admin-directives/dashboard/dashboard.html, avAdmin/admin-directives/dashboard/dashboard.js
Parent issue: https://github.com/sequentech/meta/issues/213
=> 🐞 public page is active

package.json, yarn.lock
Parent issue: https://github.com/sequentech/meta/issues/230
=> Security updates (#390)

avAdmin/admin-directives/ballot-box/view-tally-sheet-modal.html, avAdmin/admin-directives/ballot-box/write-tally-sheet-modal.html, avAdmin/admin-directives/create/create.html, avAdmin/admin-directives/dashboard/dashboard.html, avAdmin/admin-directives/dashboard/send-auth-codes-modal.js, avAdmin/admin-directives/elections/elections.html, avAdmin/admin-sidebar-directive/admin-sidebar-directive.html
Parent issue: https://github.com/sequentech/meta/issues/122
=> ✨ Multilingualism (#383)

Gruntfile.js, locales/it.json
Parent issue: https://github.com/sequentech/meta/issues/235
=> Add italian language support

avAdmin/admin-directives/dashboard/dashboard.html, avAdmin/admin-directives/dashboard/dashboard.js
Parent issue: https://github.com/sequentech/meta/issues/127
=> Fix permissions in some new actions and also in send-auth button

avAdmin/admin-directives/dashboard/dashboard.js
Parent issue: https://github.com/sequentech/meta/issues/258
=> 🐞 Spinning cog jumps during tally in admin-console

avAdmin/admin-directives/dashboard/dashboard.html
Parent issue: https://github.com/sequentech/meta/issues/258
=> Fix status bar action during tally

avAdmin/admin-directives/elcensus/add-person-modal.js, avAdmin/csv-load-service.js
Parent issue: https://github.com/sequentech/meta/issues/277
=> 🐞 Adding a voter with not required auth extra fields doesn't work

avAdmin/admin-directives/elcensus/add-person-modal.js, avAdmin/csv-load-service.js
Parent issue: https://github.com/sequentech/meta/issues/277
=> 🐞 Adding a voter with not required auth extra fields doesn't work (#405)

avAdmin/admin-directives/dashboard/dashboard.js, avAdmin/admin-directives/dashboard/send-auth-codes-modal.html, avAdmin/admin-directives/dashboard/send-auth-codes-modal.js, avAdmin/elections-api-service.js, avAdmin/must-extra-fields-service.js, avAdmin/send-messages-service.js
Parent issue: https://github.com/sequentech/meta/issues/256
=> ✨ Refresh & document OIDC support

avAdmin/admin-directives/dashboard/dashboard.js, avAdmin/admin-directives/dashboard/send-auth-codes-modal.html, avAdmin/admin-directives/dashboard/send-auth-codes-modal.js, avAdmin/elections-api-service.js, avAdmin/must-extra-fields-service.js, avAdmin/send-messages-service.js
Parent issue: https://github.com/sequentech/meta/issues/256
=> ✨ Refresh & document OIDC support (#407)

package.json, yarn.lock
Parent issue: https://github.com/sequentech/meta/issues/339
=> 🛡 Security updates (#409)

Gruntfile.js, app.js, avAdmin/admin-controller/admin-controller-spec.js, avAdmin/admin-directives/admin-field/admin-field.js, avAdmin/admin-directives/admin-fields/admin-fields.js, avAdmin/admin-directives/ballot-box/ballot-box.js, avAdmin/admin-directives/create/create.js, avAdmin/admin-directives/dashboard/dashboard.js, avAdmin/admin-directives/dashboard/send-auth-codes-modal-confirm.js, avAdmin/admin-directives/elcensus/elcensus.js, avAdmin/admin-directives/elquestions/elquestions.js, avAdmin/admin-directives/social-networks/social-networks.js, avAdmin/admin-login-controller/admin-login-controller.js, avAdmin/admin-profile-service.js, avAdmin/draft-election.js, avAdmin/elections-api-service.js, avAdmin/onboarding-tour-service.js
Parent issue: https://github.com/sequentech/meta/issues/315
=> 🐞 default translation appears when switching language for the first time

Gruntfile.js, app.js, avAdmin/admin-controller/admin-controller-spec.js, avAdmin/admin-directives/admin-field/admin-field.js, avAdmin/admin-directives/admin-fields/admin-fields.js, avAdmin/admin-directives/ballot-box/ballot-box.js, avAdmin/admin-directives/create/create.js, avAdmin/admin-directives/dashboard/dashboard.js, avAdmin/admin-directives/dashboard/send-auth-codes-modal-confirm.js, avAdmin/admin-directives/elcensus/elcensus.js, avAdmin/admin-directives/elquestions/elquestions.js, avAdmin/admin-directives/social-networks/social-networks.js, avAdmin/admin-login-controller/admin-login-controller.js, avAdmin/admin-profile-service.js, avAdmin/draft-election.js, avAdmin/elections-api-service.js, avAdmin/onboarding-tour-service.js
Parent issue: https://github.com/sequentech/meta/issues/315
=> 🐞 default translation appears when switching language for the first time (#411)

Gruntfile.js, app.js, avAdmin/admin-controller/admin-controller-spec.js, avAdmin/admin-directives/admin-field/admin-field.js, avAdmin/admin-directives/admin-fields/admin-fields.js, avAdmin/admin-directives/ballot-box/ballot-box.js, avAdmin/admin-directives/create/create.js, avAdmin/admin-directives/dashboard/dashboard.js, avAdmin/admin-directives/dashboard/send-auth-codes-modal-confirm.js, avAdmin/admin-directives/elcensus/elcensus.js, avAdmin/admin-directives/elquestions/elquestions.js, avAdmin/admin-directives/social-networks/social-networks.js, avAdmin/admin-login-controller/admin-login-controller.js, avAdmin/admin-profile-service.js, avAdmin/draft-election.js, avAdmin/elections-api-service.js, avAdmin/onboarding-tour-service.js, package.json, yarn.lock
Parent issue: sequentech/meta#567
Dependabot tickets:
- https://github.com/sequentech/admin-console/security/dependabot/36
=> Security dependencies update

package.json, yarn.lock
Parent issue: sequentech/meta#567
Dependabot tickets:
- https://github.com/sequentech/admin-console/security/dependabot/36
=> Security dependencies update (#413)

Gruntfile.js, app.js, avAdmin/admin-directives/dashboard/turnout-graph.html, avAdmin/admin-directives/dashboard/turnout-graph.js, avAdmin/admin-directives/dashboard/turnout-graph.less, avAdmin/elections-api-service.js, index.html, locales/en.json, locales/es.json, package.json
Parent issue: https://github.com/sequentech/meta/issues/206
=> ✨ Election turnout overview / graph for election managers

Gruntfile.js, app.js, app.less, avAdmin/admin-directives/dashboard/dashboard.html, avAdmin/admin-directives/dashboard/dashboard.js, avAdmin/admin-directives/dashboard/turnout-graph.html, avAdmin/admin-directives/dashboard/turnout-graph.js, avAdmin/admin-directives/dashboard/turnout-graph.less, avAdmin/elections-api-service.js, index.html, locales/en.json, locales/es.json, package.json
Parent issue: https://github.com/sequentech/meta/issues/206
=> ✨ Election turnout overview / graph for election managers (#418)

avAdmin/admin-directives/create/create.js, avAdmin/admin-directives/dashboard/dashboard.html, avAdmin/admin-directives/dashboard/dashboard.js, avAdmin/admin-directives/dashboard/dashboard.less, avAdmin/elections-api-service.js, locales/en.json, locales/es.json
Parent issue: https://github.com/sequentech/meta/issues/704
=> ✨ Check if the authorities are online (#416)

avAdmin/admin-alerts-directive/admin-alerts-directive.html, avAdmin/admin-directives/create/create.js, avAdmin/admin-directives/dashboard/dashboard.js, avAdmin/elections-api-service.js, locales/en.json, locales/es.json
Parent issue: https://github.com/sequentech/meta/issues/402
=> 🐞 Trustees struggle to respond to director

package.json, yarn.lock
Parent issue: https://github.com/sequentech/meta/issues/810
=> 🛡 Security updates (#422)

avAdmin/admin-directives/elcensus/elcensus.js
Parent issue: https://github.com/sequentech/meta/issues/1095
=> 🐞 Increase default pagination size

avAdmin/admin-directives/elcensus/elcensus.js
Parent issue: https://github.com/sequentech/meta/issues/1095
=> 🐞 Increase default pagination size (#427)

avAdmin/admin-directives/activity-log/activity-log.html, avAdmin/admin-directives/dashboard/dashboard.html, avAdmin/admin-directives/dashboard/dashboard.js
Parent issue: https://github.com/sequentech/meta/issues/751
=> 🐞 date in frontend should be formatted according to browser settings

avAdmin/admin-directives/activity-log/activity-log.html, avAdmin/admin-directives/dashboard/dashboard.html, avAdmin/admin-directives/dashboard/dashboard.js
Parent issue: https://github.com/sequentech/meta/issues/751
=> 🐞 date in frontend should be formatted according to browser settings(#429)

avAdmin/admin-directives/create/create.js
Parent issue: https://github.com/sequentech/meta/issues/752
=> ✨🐞 Improve/rethink/fix Live Preview 

avAdmin/admin-directives/create/create.js
Parent issue: https://github.com/sequentech/meta/issues/752
=> ✨🐞 Improve/rethink/fix Live Preview  (#431)

avAdmin/elections-api-service.js
Parent issue: https://github.com/sequentech/meta/issues/762
=> ✨ Separation of voting session time and bearer token lifetime

avAdmin/elections-api-service.js
Parent issue: https://github.com/sequentech/meta/issues/234
=> ✨ Voter eligibility check 

avAdmin/elections-api-service.js
Parent issue: https://github.com/sequentech/meta/issues/762
=> ✨ Separation of voting session time and bearer token lifetime (#433)

avAdmin/elections-api-service.js
Parent issue: https://github.com/sequentech/meta/issues/234
=> ✨ Voter eligibility check  (#434)

avAdmin/admin-directives/dashboard/dashboard.html
Parent issue: https://github.com/sequentech/meta/issues/2667
=> 🐞 Header in login doesn't render html
